name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/deploy-to-heroku-using-docker  
      - uses: jctaveras/heroku-deploy@v2.0.3 # This is the action
        id: heroku
        with:
          heroku_api_key: "${{secrets.HEROKU_API_KEY}}"
          heroku_app_name: "${{secrets.HEROKU_APP_NAME}}" #Must be unique in Heroku
          heroku_email: "${{secrets.HEROKU_EMAIL}}"
          dockerfile_path: '' # set the path to the folder wher the Dokerfile is located
          options: '' # Docker Build Options
