name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/deploy-to-heroku-using-docker  
      - uses: jctaveras/heroku-deploy@v1.0.0 # This is the action
        id: heroku
        with:
          api_key: "${{secrets.HEROKU_API_KEY}}"
          app_name: "${{secrets.HEROKU_APP_NAME}}" #Must be unique in Heroku
          email: "${{secrets.HEROKU_EMAIL}}"
          dockerfile: '/home/runner/work/helloheroku/helloheroku/' # set the path to the folder wher the Dokerfile is located
